target/strelka

- README.md
Added a Slack open invite link for contributors to communicate and interact with authors and each others
Manually tested to make sure the invite link work
User should get an invite link to join the Target's CFC Open Source workspace
**Checklist**
> Added Slack Invite page

- CHANGELOG.md
This commit updates the CHANGELOG with the most recent updates -- no code changes.
N/A (no code changes).
N/A
**Checklist**
> Bumped CHANGELOG

- strelka.proto
Fixes a bug in the DataRequest protobuf message.
> Fix bug in protobuf definition

- setup.py
This PR fixes #47. Prior to this, the server would throw errors indicating the file could not be located.
Cloned a fresh copy of the master branch and launched the container using the steps described in the issue.
N/A
**Checklist**
> Fix installation of taste.yara

- build/docker-compose.yaml
- configs/go/frontend/frontend.yaml
- configs/go/redis/redis.yaml
- configs/python/backend/backend.yaml
- misc/envoy/redis/envoy.yaml
- src/go/cmd/strelka-frontend/main.go
- src/go/cmd/strelka-redis/main.go
- src/go/pkg/structs/structs.go
- src/python/bin/strelka-backend
- Redis “Queue” is now Redis “Coordinator”
- “queue” key is now “tasks”
> Rename Redis components

- CHANGELOG.md
- build/python/backend/Dockerfile
- build/python/backend/requirements.txt
- src/python/strelka/scanners/scan_elf.py
This pull request transitions ScanElf from using pyelftools to LIEF (which all three executable scanners will eventually move to). We’re using LIEF 10.0dev due to requiring some incoming functionality.
Standard system testing was performed using sample Elf files, no outstanding issues identified.
```json
{
"elapsed": 1.019053,
"entrypoint": 4201077,
"header": {
"endianness": "LSB",
"file": {
"type": "EXECUTABLE",
"version": "CURRENT"
},
"flags": {
"processor": 0
},
"identity": {
"class": "CLASS64",
"data": "LSB",
"os_abi": "SYSTEMV",
"version": "CURRENT"
},
"machine": "x86_64",
"size": 64
},
"imagebase": 4194304,
"interpreter": "/lib64/ld-linux-x86-64.so.2",
"nx": true,
"pie": false,
"relocations": [
{
"address": …
```
> ScanElf rewrite

- src/go/cmd/strelka-frontend/main.go
This PR fixes a bug that causes the frontend to crash when an empty request comes in. Empty requests are commonly the result of empty files being sent to the cluster.
Full system integration testing.
N/A
**Checklist**
> Fix Frontend Crashes

- build/python/backend/requirements.txt
- src/python/strelka/scanners/scan_elf.py
- src/python/strelka/scanners/scan_macho.py
- src/python/strelka/scanners/scan_pe.py
- src/python/strelka/scanners/scan_upx.py
This pull request updates ScanPe to be more in-line with ScanElf and ScanMacho (both of which use LIEF). 
Minor changes to ScanElf, ScanMacho, and ScanUpx were also brought in with this change.
Standard system testing was performed using sample PE files, no outstanding issues identified (though it'd be nice if we had a larger variety of files to test with).
.scan.pe
```json
{
"elapsed": 2.784078,
"file_info": {
"fixed": {
"operating_systems": [
"WINDOWS32"
],
"type": {
"primary": "APP"
}
},
"string": [
{
"name": "Comments",
"value": "It's a great product with a great story to tell. I'm pumped!"
},
{
"name": "CompanyName",
"value": "Wireshark development team"
},
{
"name": "FileDescription",
"value": "Wireshark …
```
> ScanPe rewrite

- src/go/cmd/strelka-frontend/main.go
This PR deletes the cached file from the coordinator if events are retrieved from the gatekeeper.
System testing with a local cluster.
N/A
**Checklist**
> Delete cache file from Coordinator file if Gatekeeper is used

- configs/python/backend/backend.yaml
- configs/python/backend/taste/taste.yara
- docs/README.md
- src/python/strelka/scanners/scan_ini.py
This PR adds an INI file scanner and complementary backend configuration settings to enable it. 
System testing with a local cluster.
.scan.ini
```json
{
"elapsed": 0.000178,
"keys": [
{
"name": "Package",
"section": "testing",
"value": "foo"
},
{
"name": "Module",
"section": "testing",
"value": "bar"
}
]
}
```
**Checklist**
> Init ScanIni

- src/python/strelka/scanners/scan_zip.py
This PR improves the speed of decrypting files in ScanZip by removing the need to iterate the password list for each file. It also resolves a zlib error that can occur when unzipping a file with a bad password.
System testing with a local cluster and multiple encrypted Zip files.
N/A
**Checklist**
> Improves speed of decrypting in ScanZip

- configs/go/frontend/frontend.yaml
- configs/go/manager/manager.yaml
- src/go/cmd/strelka-frontend/main.go
- src/go/cmd/strelka-manager/main.go
- src/go/pkg/structs/structs.go
Frontend now has options for PoolSize and ReadTImeout, may be required to modify for large or busy clusters.
System testing with a local cluster.
N/A
**Checklist**
> Added PoolSize and ReadTimeout options

- src/python/strelka/scanners/scan_html.py
In some instances, link was initialized but had a value of None. The previous code did not account for links without content.
Executed fileshot against a local instance with affected files. Exception did not occur after fix was implemented.
N/A
**Checklist**
> Issue 104: Fox to require var link to be not None

- docs/README.md
Readme modification to provide more context for fileshot configuration. Adding in details for the "files.delay" functionality.
Not Applicable
Not Applicable
**Checklist**
> Adding description for "files.delay"

- src/python/strelka/scanners/scan_ocr.py
Fixes a broken f-string in ScanOcr.
N/A
N/A
**Checklist**
> Fix OCR return_code f-string

- src/python/strelka/scanners/scan_tnef.py
109: Adding try / except for string strip.
110: Removing data key references.
Modified scan_tnef.py to account for two exceptions:
- https://github.com/target/strelka/issues/109
- https://github.com/target/strelka/issues/110
Pushed several tnef objects through with no new or old exceptions or issues.
N/A
**Checklist**
> Fixes for Issue 109 + 110

- build/python/backend/Dockerfile
Bump yara to 3.11 to include some upstream bugfixes.
Reference: https://github.com/VirusTotal/yara/releases/tag/v3.11.0
Include a summary of the change (with required dependencies), any issues it fixes, and relevant motivation and context.
Describe the tests that you ran to verify your changes (including test configurations) and instructions so we can reproduce the tests. To assist in testing, the project maintainers may ask for file samples.
**Checklist**
> Update yara version

- configs/python/backend/backend.yaml
- configs/python/backend/taste/taste.yara
- src/python/strelka/scanners/scan_base64_pe.py
- src/python/strelka/scanners/scan_vba.py
- src/python/strelka/scanners/scan_yara.py
Added base64pe scanner to decode, then scan pe files that have been base64 encoded.
Changed olevba3 to olveba in scan_vba.py, as olevba3 is deprecated. Finally, added the ability to extract tags from yara scans and add the output to  an array like object.
Ran multiple samples from virustotal through these scanners to ensure no new errors were generated and that the files were processed properly.
XX
**Checklist**
> added base64pe scanner and changed olevba3 to olevba

- build/python/backend/requirements.txt
- configs/python/backend/backend.yaml
- src/python/strelka/scanners/scan_lnk.py
Included ScanLNK module. Credit to https://github.com/ronbarrey
Tested ~ 200 LNK files with the scanner. Getting some unicode output for one of the fields. All other output looked good.
{
"CLSID": "00021401-0000-0000-c000-000000000046",
"DriveSerialNumber": "982f9c34",
"DriveType": "DRIVE_FIXED",
"LocalBasePath": "C:\\Users\\Bob\\Desktop\\NetworkMiner_1-6-1\\NetworkMiner_1-6-1\\AssembledFiles\\10.66.162.60\\SMTP - TCP 7884\\0925emails.html",
"MAC": "e4b314533c78",
"MachineID": "8srtv2",
"PropertyStoreDataBlock": "䦙蚵᭺䤻",
"VolumeLabel": "OSDisk",
"elapsed": 0.003262
}
**Checklist**
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of and tested my code
- [ x] I have …
> adding lnkscanner

- src/python/strelka/scanners/scan_lnk.py
Added try except blocks to handle errors more verbosely and gracefully.
Updated Structs - typo was found
Removed some functionality that wasn't returning as a string or isn't fully ready for production environment. 
Added check for CommonNetworkRelativeLink
Built the container and tested on ~200 LNK files. No errors found. 
**Checklist**
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of and tested my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [N/A ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
> modifying scan_lnk scanner

- docs/README.md
- src/go/cmd/strelka-fileshot/main.go
- src/go/cmd/strelka-filestream/main.go
- src/go/cmd/strelka-frontend/main.go
- src/go/cmd/strelka-manager/main.go
- src/go/cmd/strelka-oneshot/main.go
- src/go/pkg/rpc/rpc.go
- src/go/pkg/structs/structs.go
This PR adds a strelka-oneshot cli app and documentation similar to the dead PR #31 but in go.
Also the proposed go fmt formatting of all go source files as requested in #131 is included.
Usage of strelka-oneshot has been added to the documentation.
**Checklist**
> Adding strelka-oneshot cli app & go fmt

- CHANGELOG.md
- configs/python/backend/backend.yaml
- configs/python/backend/taste/taste.yara
- docs/README.md
- src/python/strelka/scanners/scan_manifest.py
Adding scan_manifest scanner to scan Google Chrome manifest files.
Submitted manifest file through cluster to observe output.
```
...
"manifest": {
"description": "An example app to upload and publish Chrome Apps to the Web Store",
"elapsed": 0.000085,
"key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvTWT4REnE8g8VuWDWF96d1bOfpDMt9nWL2+m92a9kzmiciabfetpTk+zXsjuBNObK0Hm+KPxYfZjxIU7jCSq6UBf2W0SRmCWUtz7OSCAhpBKHTI7D4ybTbcRh41RKPjrHH7WTjNKi/x9LUjwdgROxVNdV5f1CCe2CHSUU1lZciu1FDHKz8cA+2+mAB+j4FvQT8rrbidbAs1O75w6k8d3g0Rp7SrlUXbvvemPIFnaBDGIpfdBLRJRIMk4dS5MAzsHJb4WVCW3hGdMR65x2lHMMLYVe8G8A+4lWrr/hnV4CBCs4FzudaMMXKYoEW5Atr+ES9XKPW8qxSTVM0FfZ4/q7QIDAQAB",
"manifest_version": 2,
"name": "Web Store API Sample App", …
```
> Adding scan_manifest scanner

- misc/kubernetes/README.md
- misc/kubernetes/backend-configmap.yaml
- misc/kubernetes/backend-deployment.yaml
- misc/kubernetes/coordinator-deployment.yaml
- misc/kubernetes/coordinator-service.yaml
- misc/kubernetes/frontend-configmap.yaml
- misc/kubernetes/frontend-deployment.yaml
- misc/kubernetes/frontend-service.yaml
- misc/kubernetes/gatekeeper-deployment.yaml
- misc/kubernetes/gatekeeper-service.yaml
- misc/kubernetes/logs-pvc.yaml
- misc/kubernetes/manager-configmap.yaml
- misc/kubernetes/manager-deployment.yaml
- misc/kubernetes/mmrpc-deployment.yaml
- misc/kubernetes/mmrpc-service.yaml
- misc/kubernetes/strelka-namespace.yaml
- misc/kubernetes/strelka-networkpolicy.yaml
- misc/kubernetes/yara-pvc.yaml
Adds all of the necessary example configurations to deploy Strelka on Kubernetes.
I ran the setup in Kubernetes on Docker Desktop and scanned files successfully.
No changes to output
**Checklist**
> Provide a Kubernetes deployment example

- .github/workflows/build_master_push.yml
- .github/workflows/nightly.yml
Creating Github action to test Strelka's build status each day
Github Action testing, no changes to Strelka
Github Action testing, no changes to Strelka
**Checklist**
> Create Github Action build_strelka_daily.yml

- .github/workflows/build_strelka_daily.yml
Creating Github Action to build Strelka each day to test build status
GitHub Action implementation, no changes to Strelka
GitHub Action implementation, no changes to Strelka
**Checklist**
> Create GitHub Action to Test Strelka Daily

- misc/python-client/README.md
- misc/python-client/client.py
- misc/python-client/requirements.txt
Adding a python client to the misc folder
Describe the tests that you ran to verify your changes (including test configurations) and instructions so we can reproduce the tests. To assist in testing, the project maintainers may ask for file samples.
**Checklist**
> Add Python client

- build/python/backend/Dockerfile
- build/python/backend/requirements.txt
- configs/python/backend/backend.yaml
- docs/README.md
- misc/kubernetes/backend-configmap.yaml
- src/python/strelka/scanners/scan_qr.py
Implemented ScanQR QR code file scanner. Scans images for QR codes and extracts bot the QR code type and QR code data.
Tested scanner against several images containing sample QR codes.
**Checklist**
> Adding ScanQR

- docs/README.md
Fix (very small) typos in `docs/README.md`. 
N/A.
N/A.
**Checklist**
> docs: fix typos in docs/README.md

- build/python/backend/requirements.txt
- src/python/strelka/scanners/scan_lsb.py
Vulnerable version was identified for opencsv, updating.
- Built container
- Tested relevant scanners
No output changes
**Checklist**
> Upgrading opencsv

- README.md
#188 resolved the known issue, so perhaps it can be removed. I came across this while reviewing someone's writing about Strelka. I've added a link to the bugs as a fallback.
**Checklist**
> Drops resolved known issue from README

- build/python/backend/requirements.txt
- configs/python/backend/backend.yaml
- src/python/strelka/scanners/scan_pe.py
Updating the PE scanner to:
- Provide PE security details, such as certificates.
Built and ran against 30+ PE files.
```
...
"security": {
"signers": [
{
"more_info": "http://www.microsoft.com",
"program_name": "Microsoft",
"serial_number": "1137338007247502903998857021227845427354665368",
"issuer_dn": "CN=Microsoft Windows Phone Production PCA 2012, O=Microsoft Corporation, L=Redmond, ST=Washington, C=US"
}
],
"counter_signers": [
{
"serial_number": "1137338006831431696662960583954213975565009224",
"signing_time": "2021-10-05T00:18:14.808000+00:00",
"issuer_dn": "CN=Microsoft Time-Stamp PCA 2010, O=Microsoft Corporation, L=Redmond, ST=Washington, C=US"
}
],
"certificates": [
{
"valid_to": …
```
> PE File Certificate Fix

- src/python/strelka/scanners/scan_iso.py
Updating the ISO scanner to:
- Identify possible `hidden` directories
- Identify possible metadata, such as: ISO create, modify, expire date as well as ISO label.
Built and ran against 10+ benign and malicious ISO files.
```
..
"iso": {
"elapsed": 0.032328,
"files":  [
{
"date_utc": "2022-11-17T17:48:57Z",
"filename": "/Contract",
"size": 2521
},
{
"date_utc": "2022-11-17T17:48:57Z",
"filename": "/fireman/ineligibly.tmp",
"size": 707584
},
{
"date_utc": "2022-11-17T17:46:07Z",
"filename": "/unbelt/opinionate.txt",
"size": 87900
}
],
"hidden_dirs": [
"/fireman”,
“/unbelt”
],
"meta": {
"date_created": "2022-11-18T03:00:00Z",
"volume_identifier": "CD_ROM                          "
},
"total": {
"extracted": 3,
"files": …
```
> ISO Hidden File and Metadata Update

- src/go/cmd/strelka-filestream/main.go
- src/go/cmd/strelka-frontend/main.go
- src/go/cmd/strelka-oneshot/main.go
- src/go/pkg/rpc/rpc.go
Adds comments to frontend `main.go`, filestream `main.go`, oneshot `main.go`, `rpc.go`
```
cd strelka-frontend
go build main.go
cd strelka-filestream
go build main.go
cd strelka-oneshot
go build main.go
```
No changes
**Checklist**
> Go Code Comments

- docs/README.md
Updating references to Python version requirements in docs.
N/A
N/A
**Checklist**
> README Python Version References

- src/python/strelka/auxiliary/xl4ma/xlsm_wrapper.py
- src/python/strelka/scanners/scan_xl4ma.py
When scanning some Excel workbooks, the following error was thrown:
```
Traceback (most recent call last): File "/strelka/auxiliary/xl4ma/xlsm_wrapper.py", line 34, in parse_sheets for row in self.workbook[sheet].rows: AttributeError: 'Chartsheet' object has no attribute 'rows
```
The following line is not available in all scanned workbooks: 
https://github.com/target/strelka/blob/566d7c518778dfa53e4a663ab62a5403e18a3bec/src/python/strelka/auxiliary/xl4ma/xlsm_wrapper.py#L32
Adding a check here to ensure the object is available to proceed with scanning:
https://github.com/target/strelka/blob/2e5d79eef83f93b4378fc194a5b60c4bfce310f9/src/python/strelka/auxiliary/xl4ma/xlsm_wrapper.py#L30
This was not observed in workbooks outside of `xlsm` files, so no changes to …
> ScanXL4MA Bug Fix

- src/python/strelka/scanners/scan_javascript.py
- src/python/strelka/scanners/scan_nf.py
- src/python/strelka/scanners/scan_pkcs7.py
- src/python/strelka/scanners/scan_zlib.py
Several scanners were throwing consistent unhandled exceptions leading to excessive exception logging. Additional exception handlers were added to noisiest scanners and several issues with exceptions using `self.flags()` were fixed (should have been `self.flags.append()`
```
#0 104.0 =========================== short test summary info ============================
#0 104.0 ============ 103 passed, 27 warnings in 103.35s (0:01:43) ============
```
No functional changes should appear in this change.
**Checklist**
> Scanner Specific Exception Handling Updates

- src/python/strelka/strelka.py
Quick fix for leftover print() statement.
**Checklist**
> Remove debugging statement from strelka.py

- README.md
Shows how to access Strelka UI on the main README.md, after the Quick Start
Follow instructions in the README (build strelka containers), navigate to the URL and log in successfully.
**Checklist**
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of and tested my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] My changes generate no new warnings
> Add UI doc to main README.md

- src/python/requirements.txt
- src/python/strelka/scanners/scan_pe.py
- src/python/strelka/tests/test_scan_transcode.py
Dependency bump from 8 month old version to current.
Built platform without cache and tested relevant scanners
N/A
**Checklist**
> Update Pillow Dependency

- .github/workflows/build_strelka_nightly.yml
Creates a new nightly build file for hanging off nightly email build notifications.
N/A
N/A
**Checklist**
> Create Nightly Build File

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Updates the change log with recent changes and also updates lingering dependencies that are reported by dependabot. 
Tested with local build to ensure build still runs.
N/A
**Checklist**
> Dependency and Changelog Updates
