CHANGELOG.md
Dockerfile
README.md
etc/strelka/strelka.yml
server/scanners/scan_javascript.py

This PR adds an option to deobfuscate JavaScript files. Enabling this option should improve the JavaScript parsing — by default, it will be enabled.
Tested with complex JavaScript files and compared the beautified and raw JavaScript content. All option settings (True, False, null) were also tested.
N/A
**Checklist**

Add option to deobfuscate JavaScript

---

CHANGELOG.md
etc/bro/extract-strelka.bro

This PR changes the behavior of extract-strelka.bro to temporarily disable file extraction if the size of the extraction directory becomes too large (default threshold is >50,000 files). This is to ensure the stability of Bro/Zeek in case of extended network disruptions between NSM sensor(s) and the Strelka cluster.
A variation of this change has been tested for 4+ weeks in a large-scale, production Strelka cluster. The Bro/Zeek script behaves exactly as expected (when file count threshold is met, extraction temporarily stops; when file count threshold passes, extraction starts).
**Checklist**

Add extraction toggle to extract-strelka.bro

---

CHANGELOG.md
README.md
etc/strelka/strelka.yml
server/lib.py

This commit makes two changes:
Ports have been redefined to “socket” ports. This results in no change in functionality, it’s simply a name change that should improve clarity in the configuration options.
Added options for setting ZeroMQ TCP reconnections on the task socket. This can help reduce network noise from the workers when the connection between them and the broker is disrupted.
This has been tested for 4+ weeks in a large-scale production cluster, no observable issues in performance.
N/A
**Checklist**

Add ZeroMQ reconnection options

---

server/scanners/scan_bzip2.py

This PR adds EOF error handling to the bzip2 scanner.
Append a flag to bzip2 files if the scanner encounters an end of file error.
This was tested on truncated bzip2 files.
N/A -- this causes no change to the structure of Strelka's output.
**Checklist**

Add EOF error handling to bzip2 scanner

---

requirements.txt

This commit resolves CVE-2017-18342 in pyyaml. Thanks GitHub alerts!
Bumped the version of pyyaml from 3.13, which is vulnerable to CVE-2017-18342, to 4.2b1.
Loaded up a Strelka server using 4.2b1 -- did not see any issues in loading configuration files.
N/A
**Checklist**

Bump pyyaml version to resolve CVE

---

etc/strelka/taste/taste.yara

The email tasting rule wasn't identifying my email messages because it was only looking for two specific headers, which mine didn't have.  I added a few more email-specific headers: Message-ID, Reply-To and X-Mailer.
Submitted new email samples and verified they were properly identified.  Sorry, can't share them in public.
No output changes 
**Checklist**
- [na ] I have commented my code, particularly in hard-to-understand areas
- [na] I have made corresponding changes to the documentation

Better identification of email files during tasting

---

server/scanners/scan_pe.py

Added PE version info to ScanPe scanner
I wasn't sure about adding the "no_version_info" flag since it's relatively common, but that would be easy to remove.
Unit test script coming in a second pull request
This adds a "version_info" key to the scanner.metadata output
```
"version_info": {
"CompanyName": "Google Inc.",
"FileDescription": "Google Update Setup",
"FileVersion": "1.3.33.23",
"InternalName": "Google Update Setup",
"LegalCopyright": "Copyright 2007-2010 Google Inc.",
"OriginalFilename": "GoogleUpdateSetup.exe",
"ProductName": "Google Update",
"ProductVersion": "1.3.33.23",
"LanguageId": "en"
}
```
This can be used to build Kibana visualizations like below
**Checklist**

parsing PE version info

---

etc/dirstream/dirstream.yml
strelka_dirstream.py

With the larger ecosystem of tools in mind, we have a usecase where we may want to archive the files that bro/suricata/NSM would store rather than delete them entirely. This would allow other tools to analyze the files, while preventing strelka_dirstream.py from looping over the same files over and over again. Essentially this was more or less a copy of the `delete_file()` method in strelka_distream.py with a few minor modifications.
I tested this on our suricata instance which is file carving and determined that it is indeed working. 
**Checklist**

added method to archive files with strelka_dirstream.py 

---

README.md
etc/strelka/passwords.txt
etc/strelka/strelka.yml
server/scanners/scan_zip.py

Added functionality that allows ScanZip to open password-protected zip archives. The user places possible passwords in a text file that is read by ScanZip only if it encounters a password-protected archive. Note that this list of passwords is NOT protected in any way - it is simply a list of "traditional" passwords that are used for protecting malicious files from unintended execution.
I tested this by un-zipping password-protected archives.
N/A
**Checklist**
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of and tested my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ …

Expanded ScanZip functionality to unzip password-protected archives.

---

README.md
etc/dirstream/dirstream.yml
strelka_dirstream.py

Modified the `run()` function while loop to allow for sending files recursively from directories nested below `self.directory`. This option is specified in `etc/dirstream/dirstream.yml`. I also migrated away from using `os.scandir()` to use `glob.iglob()` instead for building the file paths. Lastly, I added some logic at the end of the loop to silence debug logging if `self.sent = 0` 
Invoked the following command on our IDS server that is archiving files:
`python3 strelka_dirstream.py -d -c etc/dirstream/dirstream.yml`
Tested this with the following `dirstream.yml` configurations: 
(Recursive: False)
```
dirstream:
processes:
shutdown_timeout: 10
workers:
- directory:
directory: "/tmp/samples/"
recursive: False
source: null …
```

Add recursive functionality to dirstream

---

docs/README.md
server/scanners/scan_javascript.py

This PR resolves #20
Adds new metadata field "beautified" to ScanJavascript -- this field describes whether the scanned JS was successfully beautified. If JS was not beautified, then it is parsed as is. 
Tested with files that pass the beautification process. No deviations from the default strelka.yaml were necessary.
```
"javascriptMetadata": {
"beautified": true
}
```
**Checklist**

Add “beautified” to ScanJavascript

---

etc/strelka/taste/taste.yara

Email headers are case-insensitive, but the tasting rule was written as case-sensitive.  This just corrects that, and adds the "fullword" qualifier as an additional check that it's matching correctly.
I ran it these in strelka with email messages that didn't match the case in the rules, and they worked.
No changes 
**Checklist**
- [na] I have commented my code, particularly in hard-to-understand areas
- [na] I have made corresponding changes to the documentation

Updated email tasting rules because headers are case insensitive

---

etc/strelka/strelka.yml
server/lib.py

This allows the option to output logs in UTC or the system time on the server. 
Modified server/lib.py to grab log_timestamp_utc variable from strelka.yml. datetime adjusted based on variable (datetime.utcnow vs datetime.now).
Added strelka.yml with log_timestamp_utc variable with "True" as default.
Tested changes on a CentOS 7 VM. Left "True" default, logs came in as UTC. Modified log_timestamp_utc to False, restarted Strelka, logs came in as local system time.
UTC:
{"startTime": "2019-03-18T21:57:10", "finishTime": "2019-03-18T21:57:22", "elapsedTime": 11.958862, "server":
System Time:
{"startTime": "2019-03-18T15:58:28", "finishTime": "2019-03-18T15:58:39", "elapsedTime": 11.037415, "server":
**Checklist**
- [ X …

Added option to allow system time vs UTC on log output. UTC default.

---

Dockerfile

Modified DockerFile to allow the option to set the timezone (default UTC). Needed to add "ENV DEBIAN_FRONTEND=noninteractive" variable to make the install of tzdata package non-interactive. Needed to add necessary packages to modify timezone.
Time Zones are set using the usual Continent/Region format
Tested with "UTC" "zoneinfo/UTC" Then with "America/Denver" "zoneinfo/America/Denver"
RUN apt-get install -y software-properties-common apt-utils locales tzdata \
&& echo "UTC" > /etc/timezone \
&& ln -fs /usr/share/zoneinfo/UTC /etc/localtime \
&& dpkg-reconfigure -f noninteractive tzdata
**Checklist**

Added option to set Time Zone

---

requirements.txt

Switched from pyopenssl version 18 to a forked version of the package -- “get_certificates” doesn’t exist in the main repository :/
Validated using Wireshark 64-bit EXE as a sample (https://2.na.dl.wireshark.org/win64/Wireshark-win64-3.0.1.exe)
N/A
**Checklist**

Switch pyopenssl to private repo

---

src/python/bin/strelka-backend
src/python/strelka/scanners/scan_docx.py

ScanDocx had two bugs:
* Timestamps were not converted to Unix / epoch during transition from ZeroMQ to gRPC
* Extracted body text was missing newline characters
In fixing the previous two bugs, a third bug was found in bin/strelka-backend:
* ‘re’ was not imported
Wrote a debug scanner called 'ScanWrite' (which writes files to disk) to validate that ScanDocx was incorrectly extracting document body text. Upon fixing it, used the same scanner to valdiate that the body text was correctly extracted.
```json
{
"author": "Joshua.Liburdi",
"created": 1559319600,
"elapsed": 0.009578,
"last_modified_by": "Joshua.Liburdi",
"modified": …
```

Fix ScanDocx bugs

---

src/go/cmd/strelka-frontend/main.go
src/python/bin/strelka-backend
src/python/strelka/strelka.py

Reformat JSON Events

---

src/python/strelka/scanners/scan_pdf.py

This commit fixes a bug in some ScanPdf flags — some reference the PDF file’s object ID and need to be f-strings.
Standard system testing was performed using sample PDF files, no outstanding issues identified.
N/A
**Checklist**

Fix ScanPdf f-string bug

---

src/python/strelka/scanners/scan_elf.py

During a review of ScanMacho, multiple issues were found in ScanElf — relocation symbol and section names were not written correctly, symbol count was missing from the total, and alignment was missing from sections.
Standard system testing was performed using sample Elf files.
```json
"total": {
"relocations": 78,
"sections": 29,
"segments": 8,
"symbols": 81
}
```
```json
{
"alignment": 1,
"entropy": 4.290381706873078,
"name": ".shstrtab",
"offset": 16152045,
"size": 255,
"type": "STRTAB"
}
```
**Checklist**

Fix ScanElf Dictionary Issues

---

configs/go/fileshot/fileshot.yaml
configs/go/filestream/filestream.yaml
docs/README.md
src/go/cmd/strelka-fileshot/main.go
src/go/cmd/strelka-filestream/main.go
src/go/pkg/structs/structs.go

This PR makes the server dial timeout a configurable option for both Go clients. This is useful for very slow connections.
System testing with a local cluster, tested both fileshot and filestream.
N/A
**Checklist**

Add server dial timeout option

---

src/python/strelka/scanners/scan_ini.py

This PR adds two new fields to ScanIni, a 'comments' field and 'sections' field. It also improves the parsing for no named keys.
System testing with a local cluster and multiple dummy INI files.
.scan.ini
```json
{
"comments": [
"# this is",
"# a comment!"
],
"elapsed": 0.000162,
"keys": [
{
"name": "Package",
"section": "testing",
"value": "foo"
},
{
"name": "Module",
"section": "testing",
"value": "bar"
},
{
"name": "test",
"section": "testing"
},
{
"section": "testing",
"value": "test2"
}
],
"sections": [
"testing"
]
}
```
**Checklist**

Added new fields to ScanIni

---

configs/python/backend/backend.yaml
configs/python/backend/taste/taste.yara
docs/README.md
src/python/strelka/scanners/scan_zlib.py

This PR adds a Zlib scanner, similar in functionality to the other compression scanners (gz, lzma, etc.).
System testing with a local cluster and multiple Zlib files.
.scan.zlib
```json
{
"elapsed": 0.000664,
"flags": [],
"size": 16
}
```
**Checklist**

Zlib Scanner

---

src/python/strelka/scanners/scan_mmbot.py

ScanMmbot fields are now properly nested according to logical group
System testing with a local cluster and multiple Mmbot files.
.scan.mmbot
```json
{
"confidence": 0.89,
"elapsed": 0.062427,
"entropy": {
"characters": 2.37,
"functions": 0,
"words": 3.35
},
"features": "minor_horizontalalignment_redoaction_isbroken_formshowconstants",
"prediction": "benign",
"ratio": {
"comments": 0,
"functions": 0
},
"total": {
"comments": 0,
"functions": 0,
"locations": 8
}
}
```
**Checklist**

Modified ScanMmbot fields

---

src/python/strelka/scanners/scan_macho.py

This commit improves the nesting event structure for the ScanMacho field commands.dynamic_symbol
System testing with a local cluster and multiple Mach-O files.
.scan.macho.commands.dynamic_symbol
```json
{
"command": {
"offset": 1684,
"size": 80
},
"offset": {
"relocation": {
"external": 0,
"local": 0
},
"symbol": {
"external": 0,
"indirect": 72172
},
"table": {
"module": 0
},
"toc": 0
}
}
```
**Checklist**

Modify ScanMacho dynamic symbol

---

src/python/strelka/scanners/scan_bzip2.py
src/python/strelka/scanners/scan_gzip.py
src/python/strelka/scanners/scan_lzma.py

ScanBzip2 “decompressed_size” is now “size”
ScanGzip “decompressed_size” is now “size”
ScanLzma “decompressed_size” is now “size”
**Checklist**

Renamed decompressed_size to size

---

src/python/strelka/scanners/scan_pe.py

Fixes an AttributeError that occurs when an MZ file does not have base of data information.
System testing with a local cluster and an MZ file that causes the error.
N/A
**Checklist**

Fix ScanPe header AttributeError

---

configs/python/backend/backend.yaml
configs/python/backend/taste/taste.yara
docs/README.md
src/python/strelka/scanners/scan_plist.py

This PR adds a property list (plist) scanner, it supports both binary and XML plists and user-defined key logging.
System testing with a local cluster and multiple OSX plist files.
.scan.plist
```json
{
"elapsed": 0.000195,
"keys": [
"Label",
"ProgramArguments",
"Sockets",
"EnableTransactions"
],
"label": "com.openssh.ssh-agent",
"program_arguments": [
"/usr/bin/ssh-agent",
"-l"
]
}
```
**Checklist**

Init ScanPlist

---

configs/python/backend/backend.yaml

This commit removes binary plist files from Exiftool parsing in the default backend.yaml — this is replaced by ScanPlist.
System testing with a local cluster and multiple OSX plist files.
N/A
**Checklist**

Remove binary plist from Exiftool

---

configs/python/backend/backend.yaml
docs/README.md
src/python/strelka/scanners/scan_base64.py
src/python/strelka/scanners/scan_html.py

This commit addresses the payload delivery technique described here: https://isc.sans.edu/forums/diary/Interesting+JavaScript+Obfuscation+Example/25020/. This required the addition of ScanBase64.
System testing with a local cluster and files that contain the technique described above.
N/A
**Checklist**

Add support for decoding embedded hyperlinks

---

configs/python/backend/backend.yaml
docs/README.md
src/go/cmd/strelka-frontend/main.go
src/python/strelka/scanners/scan_email.py
src/python/strelka/scanners/scan_exiftool.py
src/python/strelka/scanners/scan_html.py
src/python/strelka/scanners/scan_jar_manifest.py
src/python/strelka/scanners/scan_pe.py
src/python/strelka/scanners/scan_plist.py
src/python/strelka/scanners/scan_yara.py

This pull request gives administrators more control over which key-value pairs are logged in scanners that support key-value pairs (ScanEmail, ScanExiftool, ScanJarManifest, ScanPe, ScanPlist, ScanYara). This also updates the ScanExiftool default config to less liberally log key-value pairs.
System testing with a stage cluster receiving many types of files.
N/A
**Checklist**

Improve key-value parsing

---

src/python/strelka/scanners/scan_pdf.py

A reference to the "data" variable caused issues with pdfminer while attempting to extract text from a PDF. This error would only occur when the user sets "extract_text" to True from the ScanPdf options in backend.yml. To fix this, we are instead replacing "data" with "pdf_io", an in-memory stream of the data object. This is readable by pdfminer, whereas the data object was not.
Change was made on a local instance. No errors were observed after making the change, and the error that appeared previously was removed. Logging was used to examine the output, which displays proper text extraction.
Text extraction noted in header.header:
`"scan": {
"entropy": {
"elapsed": 0.000155,
"entropy": 4.953766942682617
},
"hash": { …

Changing page variable to in-memory stream

---

src/python/strelka/scanners/scan_plist.py

Seen in invalid XML files, will throw errors on the backend. Attributing exception to a flag.
Adding in a try / except for plist loading to solve backend exceptions noted in https://github.com/target/strelka/issues/103.
Built and executing fileshot against several hundred plist files, including one invalid plist file.
```  
"plist": {
"elapsed": 0.001473,
"flags": [
"invalid_format"
]
}
```
**Checklist**

Exception handling for plist load failure

---

src/python/strelka/scanners/scan_docx.py

This change was implemented as part of researching a fix for the issue identified in https://github.com/target/strelka/issues/121. That issue was opened based on corrupted documents which this scanner should not and will not support - however, additional error handling was implemented to ensure that the throw exception will be caught and saved as a flag.
Corrupted .docx files were submitted through the a local cluster from release 0.19.08.27.
```
"scan": {
"docx": {
"elapsed": 0.00444,
"flags": [
"bad_doc"
]
}
```
**Checklist**

Adding error handling for corrupt documents

---

src/go/cmd/strelka-frontend/main.go
src/go/cmd/strelka-manager/main.go

The [go-redis](https://github.com/go-redis/redis) package [was updated to accept `context.Context` as the first argument for all commands](https://github.com/go-redis/redis/commit/a8cd04089222eb178f2f254acddbdea0b4ce41ea). This update caused an exception in the previous code which did not pass a Context object to several commands. 
Examples of exceptions seen:
```
./main.go:40:19: not enough arguments in call to cd.cmdable.Ping
have ()
want (context.Context)
./main.go:46:35: not enough arguments in call to cd.cmdable.ZRemRangeByScore
have (string, string, string)
want (context.Context, string, string, string)
```
[To fix this issue](https://github.com/go-redis/redis/issues/1333#issuecomment-633171474), all files using go-redis were updated with the appropriate …

Updated to reflect change in command structure

---

build/python/backend/Dockerfile
configs/python/backend/backend.yaml
docs/README.md
src/python/strelka/scanners/scan_floss.py

[FireEye FLOSS](https://github.com/fireeye/flare-floss) scanner developed to scan and collect obfuscated strings from binaries:
This change required the following:
- Update Backend Dockerfile to install FireEye FLOSS binary. Tool is not supported in Python3, requiring the binary to be installed with additional permissions.
- Developed FLOSS scanner
- Updated backend configuration, but disabling FLOSS as it is time consuming. **Enable only knowing that this should be run on specific types of executables or with the understanding that it will take considerable time to run per executable. (Averaging 7-40 seconds)**
Built and tested on the Master branch. No new exceptions thrown.
_Stack Strings_
```
"floss": { …
```

Add FireEye Floss Scanner

---

CHANGELOG.md
build/go/frontend/Dockerfile
build/go/manager/Dockerfile
src/go/cmd/strelka-frontend/main.go
src/go/cmd/strelka-manager/main.go

The dependency `go-redis` for `strelka-frontend` and `strelka-manager` has recently been updated, which caused issues in compilation of the `strelka` cluster (https://github.com/go-redis/redis/issues/1534). A fix has been implemented to use a previous release of `go-redis` (`v8`). While this should act as a fix, it should also be temporary until an alternative solution has been identified or `go-redis` fixes this issue.
Related Issue: https://github.com/target/strelka/issues/142
- Destroyed and rebuilt all strelka images to identify additional errors.
- Ran multiple scanners to identify additional errors and review output changes.
No output changes.
**Checklist**

Bug Fix: Redis Versioning

---

docs/README.md
src/python/bin/strelka-backend

This change provides the option to prevent `strelka-backend` from shutting itself down after `max_files` or `time_to_live` has been reached.
Rebuilt the `strelka-backend` image and tested using a value of `0` for max_files and time_to_live in `backend.yml`
**Checklist**

Add Option to Disable Strelka Backend Shutdown

---

build/python/backend/Dockerfile
build/python/mmrpc/Dockerfile

Also: Adding `noninteractive argument` to prevent timezone / prompts
Updating Ubuntu image to 20.04 as some dependencies were having issues with the previous Ubuntu image.
Implemented changes and tested 12+ scanners in a localized cluster.
N/A
**Checklist**

Updating images due to dependency issues

---

build/python/backend/requirements.txt
build/python/mmrpc/requirements.txt

Recent versions of cryptography have shown failures in the rust requirements / installations. Pinning for now.
Updating backend and mmrpc requirements with a pinned cryptography.
Built Strelka locally and within Github Actions
N/A
**Checklist**

Pinning Cryptography Dependency

---

build/go/fileshot/Dockerfile
build/go/filestream/Dockerfile
build/go/frontend/Dockerfile
build/go/manager/Dockerfile
build/python/backend/Dockerfile
build/python/mmrpc/Dockerfile

go containers had issues building due to an inconsistent implementation go modules. Refactored all go Dockerfiles and attempted to normalize them.
Rebuilt Strelka, no issues
N/A
**Checklist**

Refactoring Dockerfiles

---

build/go/filestream/Dockerfile
docs/README.md
src/go/cmd/strelka-filestream/main.go
src/go/pkg/rpc/rpc.go
src/go/pkg/structs/structs.go

Allows files to be moved to another directory (out of staging) after being submitted for scanning.  This directory can be specified by adding `files.processed` to `filestream.yaml`.  
Tested  with:
- `/nsm/strelka/unprocessed` as `files.patterns`
- `/nsm/strelka/staging` as `staging`
- `/nsm/strelka/processed` as `files.processed`
1. `echo "MyTestFileContent" > /nsm/strelka/unprocessed/mytestfile`
2. File is moved by Strelka into `/nsm/strelka/staging`.
3. File is submitted for scanning, then moved to `/nsm/strelka/processed`.
Shout-out to @rwwiv for his help with this,  bc I can't Golang good 😆 .
**Checklist**

Add option to move files to processed directory after submission

---

build/go/oneshot/Dockerfile
docs/README.md

Strelka oneshot required a `go build` and did not support Docker (unlike `fileshot`). Implemented a Dockerfile.
1. Cloned the repository
```sh
git clone https://github.com/target/strelka.git /opt/strelka/
```
2. Built the container
```sh
cd /opt/strelka/
docker build -f build/go/oneshot/Dockerfile -t strelka-oneshot .
```
N/A
**Checklist**

Adding client oneshot Dockerfile

---

build/go/fileshot/Dockerfile
build/go/filestream/Dockerfile
build/go/frontend/Dockerfile
build/go/manager/Dockerfile
build/go/oneshot/Dockerfile
src/go/cmd/strelka-fileshot/go.mod
src/go/cmd/strelka-filestream/go.mod
src/go/cmd/strelka-frontend/go.mod
src/go/cmd/strelka-manager/go.mod
src/go/cmd/strelka-oneshot/go.mod

The `go.mod` file was originally generated with:
`go mod init strelka-manager && go mod tidy`
The `go.mod` file is now copied to the build container instead of being
regenerated with every build. This enables quicker builds and makes
things like version pinning more straightforward.
**Dockerfile Updates:**
- The `RUN go mod download` step creates a cached image layer 
with external dependencies downloaded. The cache should enable 
quicker builds whenever the imports remain unchanged. 
- Set the container entrypoint as an example. 
This is currently being overridden by docker-compose.
- It's important to note that if any of these containers
are updated in the future that the `mod` files be updated
as well.
Built and ran fresh images …

Refactoring go Dockerfiles / adding modfiles

---

build/docker-compose.yaml

Ran into an issue during local testing where the `Docker` containers
were provided the name prefix `backend-` rather than `strelka-` for
an unknown reason. Container names with the `strelka-` prefix are
currently hardcoded in the `config` files, which led to the containers
not being able to identify eachother.
The container names are now hardcoded in the `compose` file.
Built and ran fresh images with several hundred scans over a period 
of an hour. No issues.
N/A
**Checklist**

Hardcoding container names

---

build/python/backend/requirements.txt
configs/python/backend/logging.yaml
misc/kubernetes/backend-configmap.yaml
src/python/strelka/scanners/scan_pdf.py

The current ScanPDF scanner utilizes the package: `pdfminer.six`.
It's implementation in Strelka resulted in one of the
longest running scanners in the Strelka scanner suite. A replacement
effort was made to identify another PDF library that provided similar
requirements (text, url, annotation extraction) but with an increased
runtime.
The following libraries were tested:
1. PDFPlumber
2. PDFQuery
3. PDFRW
4. PDFToText
5. PDFX
6. PikePDF
7. PyMuPDF
8. PyPDF2
While most of these fit the basic requirements needed to replace
`pdfminer.six`, the package `PyMuPDF` was selected from a series
of performance tests to be the replacement. 
An example of the tests can be summed up with the following metric
to display the performance increase:
**Test: Load and parse a 50 page …

ScanPDF Replacement

---

build/python/backend/Dockerfile
build/python/mmrpc/Dockerfile

* Reduces time to REBUILD from ~8 minutes to ~11 seconds upon creating new or modifying scanner.
* Follow's Dockerfile best practices by layer caching dependencies. 
* Should make new scanner development more efficient for editing, testing, modifying.
* Forked the repo, testing building with and without changes, still builds OK and is drastically faster on REBUILDS.
* No changes to final built images
**Checklist**
- [ * ] My code follows the style guidelines of this project
- [ * ] I have performed a self-review of and tested my code
- [ * ] I have commented my code, particularly in hard-to-understand areas
- [ * ] I have made corresponding changes to the documentation
- [ * ] My changes generate no new warnings

Improving Dockerfiles for Rebuilds

---

CHANGELOG.md
src/python/strelka/scanners/scan_pe.py

Refactor scan pe

---

build/docker-compose.yaml
configs/python/backend/rules.yara

Adds a rules.yara file to the backend, and mounts the file in the backend's /etc/yara directory to ensure there is at least one rule. Yara rules can be added without having to rebuild the container, just must restart before rescanning a file. 
I ran built strelka before and after changes to verify it works as intended.
Changes the scan yara from "compiling error" to show the test rule result.
**Checklist**
- [] I have made corresponding changes to the documentation

adding basic yara functionality by default

---

CHANGELOG.md
build/python/backend/Dockerfile

Exiftool version 12.25 was removed by the vendor and was causing new builds of Strelka to fail. Updating to the latest version (12.28) fixes this issue.
Updated exiftool, built Strelka, and scanned file with exiftool scanner.
N/A
**Checklist**

Hotfix exiftool update 12.28

---

build/python/backend/Dockerfile
configs/python/backend/backend.yaml
configs/python/backend/taste/taste.yara
src/python/strelka/scanners/scan_encrypted_doc.py
src/python/strelka/scanners/scan_encrypted_zip.py
src/python/strelka/scanners/scan_zip.py

Include a summary of the change (with required dependencies), any issues it fixes, and relevant motivation and context.
This PR does 3 major changes:
1. It install john the ripper (latest version) from source into the worker image.
2. It removes the native zip cracking in ScanZip, and removes the native scanEncryptedDocument scanner
3. It uses custom yara rules to detect encrypted zip and word documents, and uses JTR to do a dictionary attack instead of a python loop. It is much more efficient and performant (see testing). It also has the option to do brute force attacks, though these are commented in the backend.yaml by default.
Describe the tests that you ran to verify your changes (including test configurations) and instructions …

Adding John the Ripper for Dictionary attacks & Option for Bruteforcing.

---

build/python/backend/requirements.txt
build/python/mmrpc/Dockerfile
build/python/mmrpc/requirements.txt

This change reflects issue #187, a failure to compile the `mmrpc` image due to a compilation issue with `grpcio`. Adding the `build-essentials` package fixes this issue. 
1. Built container (with PyMuPDF removed - PDF Scanner - See #188 for that issue)
2. Allow cluster to run for 10+ minutes while submitting several different filetypes with fileshot. 
N/A
**Checklist**

Grpcio arm compilation fix

---

src/python/strelka/scanners/scan_javascript.py

Fixes a bug in the javascript scanner preventing regular expressions from being added to the scan results.
- Created a test file with a regular expression
- Ran fileshot and verified the regular expression is included the strelka.log
**Checklist**

bugfix: javascript scanner regex

---

build/python/backend/Dockerfile

* Twice we've seen a build w/ JTR apparently unstable.
* It's unclear if this is a build issue, or a result of grabbing
a bad version (as we were just grabbing the repo head).
* This ensures we grab the same commit, so if we continue to see
issues we can go from there.
* There are no even halfway recent tags so the commit is arbitrary.
* Also changes the repo from magnumripper/JohnTheRipper to openwall/john
as that's where the old repo forwards to.
* And grab a single commit to speed things up (239 MB -> 140 ish MB).
I've been running & rebuilding Strelka w/ these changes. This doesn't seem to have resolved JTR build issues but it may remove some possible causes.
N/A
**Checklist**

Use a specific version of JTR (#13)

---

build/python/backend/Dockerfile

ExifTools requires a perl library "Archive" to successfully inspect some word documents ([1]). This PR installs the required library in the Docker build.
This thread pretty much describes the symptom and how to fix it: https://exiftool.org/forum/index.php?topic=5087.0
1. Some quick testing suggests `docx` and `docm` files require the extension, but it's probably more complex than that. I have a `doc` file which has the same output before/after the chance, and doesn't include any `zip` fields. 
I tested this by just doing docker run on before/after images and then running `exiftool` within.
[Results w/o Archive library](https://gist.github.com/cameron-dunn-sublime/1055bc1482804cebf6868be1e190c206)
[Result w/ Archive …

Install Archive library for ExifTools

---

build/python/backend/requirements.txt
src/python/strelka/scanners/scan_elf.py

Adding fix for scan elf / logging disable

---

.gitattributes
build/python/backend/Dockerfile
build/python/backend/requirements.txt
configs/python/backend/backend.yaml
scan_bmp_eof.py
scan_lsb.py
scan_nf.py
scan_png_eof.py

As a capstone project for the University of Minnesota, we added 3 algorithms to Strelka: Beyond End-of-file, Least Significant Bit, and Noise Floor. There was one additional dependency of OpenCV2. A version of OpenCV was already included, but was not the correct version for our implementation.
We created several images that were designed to cause the tests to flag the image in the resulting strelka.log file. These were tested repeatedly to ensure Strelka doesn't crash and produces the correct output.
- Add .gitatributes file to fix LE issues
Include a summary of the change (with required dependencies), any issues it fixes, and relevant motivation and context.
Describe the tests that you ran to verify your changes (including test …

Adding Steganographic Support

---

.gitignore
build/python/backend/requirements.txt
src/python/bin/strelka-backend
src/python/strelka/strelka.py

Replaces `interruptingcow` with `signal` to handle scanner timeouts using SIGALRM. The use of `interruptingcow` results in python deprecation warnings, and the library has not been updated since 2018.
This PR also removes the the `build` directory from `.gitignore`. Files in this directory should be under version control.
- Add a sleep call to a Scanner configured to run longer than the Scanner's timeout - it throw an exception, and append a "timed_out" flag
- Run a scanner that completes in the allotted time - it should not raise a ScannerTimeout exception
- Explicitly throw an exception within a scanner - it should not append a "timed_out" flag. The signal should be cleared upon a non-ScannerTimeout exception
**Checklist**

Replace interruptingcow with signal

---

README.md
docs/README.md

The home page for the Assemblyline project has migrated from bitbucket to github. The link can be updated to reflect this change.
No tests were ran but the markdown files should hopefully still render correctly.
N/A.
**Checklist**

Updating the link to Assemblyline

---

build/python/backend/requirements.txt
src/python/strelka/scanners/scan_email.py

Email scanner was using dynamic population of output using unspecified key:value pairs. While this allowed for more data to be extracted from email headers, it was providing inconsistent results making it more difficult to build confident detection. By specifying fields to be collected, users can now search for specific fields.
Tested against 12+ .EML and other email files.
ScanEmail
```
{
"attachments": {
"filenames": [
"test.pdf"
],
"hashes": [
"ee6a929959c631f2b6bcad4bf105d822"
],
"totalsize": 28890
},
"body": "Hello, Buenos Dias, Bonjour! J\r\n\r\n\r\nPlThis is a test email.\r\n\r\n\r\nBest Regards\r\nYour account manager\r\nTester\r\n",
"date_utc": "2022-05-16T18:15:35.000Z",
"elapsed": 0.088485,
"from": …
```

Updating email scanner

---

configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_iso.py

A bug prevented extraction (and recursive extraction of subfiles) for different types of ISO files. This fix attempts to provide support for multiple ISO path types.
Executed updated scanner against multiple types of ISO files and confirmed output works and subfiles are also extracted.
N/A
**Checklist**

Adding in fix for iso extraction

---

src/python/strelka/scanners/scan_zip.py

Updating the ZIP scanner to:
- Allow for password extraction given a password in `passwords.dat`
- Provide compression and file listing details per observed file
Built and ran against 20+ Zip files and encrypted files.
```
..
"zip": {
"compression_rate": 1.39,
"elapsed": 0.020369,
"files": [
{
"compression_rate": 1.39,
"compression_size": 1205,
"file_name": "base64.txt",
"file_size": 1222
}
],
"total": {
"extracted": 1,
"files": 1
}
...
```
**Checklist**

Adding Compression to ZIP Files

---

src/python/strelka/scanners/scan_pdf.py

Update phone_number regular expression in `ScanPDF` to fix warning observed during tests:
```
=============================== warnings summary ===============================
scanners/scan_pdf.py:14
/strelka/strelka/scanners/scan_pdf.py:14: DeprecationWarning: invalid escape sequence '\+'
"\+?(?:\d{1,2})?\s?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{2,4}?\-?\d{2,4}?",
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 31 passed, 1 warning in 5.27s =========================
```
The updated regular expression will match phone numbers that are formatted in a variety of ways, including:
+1 (123) 456-7890
(123) 456-7890
123-456-7890
123 456 7890
123.456.7890
Submitted several PDFs with phone numbers to …

ScanPDF: Modification of regex throwing warning

---

src/python/strelka/scanners/scan_pdf.py
src/python/strelka/scanners/scan_qr.py

Update url regular expression in `ScanQR` to fix warning observed during tests:
```
=============================== warnings summary ===============================
/strelka/strelka/scanners/scan_qr.py:19: DeprecationWarning: invalid escape sequence '\/'
URL_REGEX = '^((https?|ftp|smtp):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*'
```
The updated regular expression will match the same addresses as before, it's just removing extraneous escape characters.
Submitted several QR documents to Strelka. 
N/A
**Checklist**

ScanQR: Modification of regex throwing warning

---

build/python/backend/Dockerfile

Adding Cmake to Dockerfile for Python build to fix an issue with lief install.
Closes #265
Running ` docker-compose -f build/docker-compose.yaml build` outputs 
```Building 1563.3s (46/46) FINISHED```
n/a
**Checklist**

Add Cmake to dockerfile for Lief

---

src/python/strelka/tests/fixtures/test.xml
src/python/strelka/tests/test_scan_xml.py

Created a test for the xml scanner, 'test_scan_xml.py', with a corresponding test file, 'test.xml'.
Difference test on the expected output of the xml scanner and the output of the test.xml file. 
docker-compose -f ./build/docker-compose.yaml build backend
No change to Strelka's output. 
**Checklist**

Added fixtures/test.xml and test_scan_xml.py

---

src/python/strelka/scanners/scan_jpeg.py
src/python/strelka/tests/test_scan_jpeg.py

ScanJpeg improvements, Fix for incorrect EOI marker

---

build/python/backend/setup.py
build/python/mmrpc/setup.py
src/python/setup.py

Referenced in #249, the following warnings were thrown upon build:
```
docker-compose build
...
strelka.tests.__pycache__.test_scan_docx.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_gif.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_html.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_iso.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_jpeg.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_msi.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_pe.cpython-310: module references __file__
strelka.tests.__pycache__.test_scan_png_eof.cpython-310: module references __file__ …
```

Adding zip_safe flag to setuptools prevent "module references __file__" warnings 

---

src/python/strelka/scanners/scan_exception.py
src/python/strelka/strelka.py
src/python/strelka/tests/__init__.py
src/python/strelka/tests/test_scan_exception.py

Fix Uncaught Exceptions in strelka.py

---

src/python/strelka/strelka.py

When pulling a scanner object from cache, `distribute()` clears the `files` property before use.
```python
name = scanner['name']
und_name = inflection.underscore(name)
scanner_import = f'strelka.scanners.{und_name}'
module = importlib.import_module(scanner_import)
if und_name not in self.scanner_cache:
attr = getattr(module, name)(self.backend_cfg, self.coordinator)
self.scanner_cache[und_name] = attr
options = scanner.get('options', {})
plugin = self.scanner_cache[und_name]
plugin.files = []
```
Fixes #292
```
./strelka-oneshot -l - -f src/python/strelka/tests/fixtures/test.html | wc -l
2
./strelka-oneshot -l - -f src/python/strelka/tests/fixtures/test.html | wc -l
2
./strelka-oneshot -l - -f …
```

Clear files from cached scanners in distribute()

---

README.md

Commit https://github.com/target/strelka/commit/0097cacc491fb990d4337006c8827d1722838a9d uses the syntax `list[dict]` which is only supported after Python 3.9.
Update readme with correct minimum Python version.
No code change included.
N/A
**Checklist**

Python 3.9 is needed due to a recent commit

---

configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_javascript.py
src/python/strelka/tests/test_scan_javascript.py

With no limits set for the `string` fields (e.g., `tokens`, `strings`) in `ScanJavascript`, events have been observed with well over thousands of objects in their associated fields. While this may be useful for some use cases, by default it may be advisable to not collect so many objects. The following modification were implemented:
- Default limit (`50`) for amount of strings per field to be collected from `ScanJavascript` session. Configurable in `backend.yml`
- Strings are distinct
The following fields are limited:
- tokens
- keywords
- strings
- identifiers
- regular_expressions
Created test: `test_scan_javascript_character_limits` in `test_scan_javascript.py` that ensures that the limit functions properly.
``` …
```

Limiter for Javascript Output, Tests, Formatting

---

src/python/strelka/scanners/scan_iso.py
src/python/strelka/tests/test_scan_iso.py

As ISO files do not store timezone data, including a Zulu time (`Z`) in times is not completely accurate and may lead to incorrect assumptions about file times. 
- Removing Zulu reference from times from `ScanIso`
- Updating `ScanIso` tests to reflect change
- Formatting `ScanIso` with `black`
Executed `pytest -s src/python/strelka/tests/test_scan_iso.py`
```
(virtualenv) desktop:strelka test$ pytest -s src/python/strelka/tests/test_scan_iso.py 
==================================================================================================================================== test session starts ===================================================================================================================================== …
```

ScanIso Timezone Removal

---

src/python/strelka/tests_configuration/test_scanner_assignment.py
src/python/strelka/tests_configuration/test_taste.py

Tests were not assigned for ScanOnenote. This change adds the onenote test files and expected tastes for the scanner.
```
docker-compose -f build/docker-compose.yaml build --build-arg CONFIG_TESTS=true backend
...
#0 104.9 ================= 104 passed, 27 warnings in 104.18s (0:01:44) =================
```
**Checklist**

ScanOnenote Test Configuration Update

---

src/python/strelka/strelka.py
src/python/strelka/tests_configuration/test_scanner_assignment.py
src/python/strelka/tests_configuration/test_taste.py

Update config tests for ScanTranscode fixtures.
Restore missing check_scanners() code (removed accidentally in Telemetry PR).
Remove double coordinator upload (added accidentally in Telemetry PR).
Tests work, I should use them.
```
docker-compose -f build/docker-compose.yaml build --build-arg CONFIG_TESTS=true backend
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /strelka
plugins: mock-3.10.0, unordered-0.5.2
collected 182 items
tests_configuration/test_distribute.py .
tests_configuration/test_scanner_assignment.py ......................................................................................... …
```

Update Tests, Telemetry PR Bugs

---

build/docker-compose.yaml

In Strelka's default `docker-compose.yml` file, changing the local pull and build of the [Strelka UI project ](https://github.com/target/strelka-ui) to a prebuilt docker image to reduce build time and potential errors when compiling the Strelka UI container.
Built Strelka with `--no-cache` using the Strelka UI image referenced in this PR. Loaded http://localhost:9980/, logged in with `strelka:strelka` and submitted a file successfully through the Strelka pipeline.
**Checklist**

Use Strelka UI Docker Image in docker-compose.yml

---

configs/python/backend/backend.yaml

Prior to this request, only the `ScanZip` scanner was enabled to use a provisioned password file (default: `passwords.dat`). As `ScanZip` does not perform any password extraction, and instead waits for `ScanEncryptedZip`, this meant that the passwords file was never used. By enabling the `password_file` for `ScanEncryptedZip`, we are now attempting to open encrypted zip files with the provided password file, prior to brute forcing (if enabled).
As the password file functionality also exists in `ScanEncryptedDoc`, that has also been enabled by default.
Started a local Strelka cluster and passed several password encrypted zip files through the Web UI. Prior to this change
Prior to fix (`ScanEncryptedZip`)
After fix (`ScanEncryptedZip`) …

Adding Passwords File to Additional Scanners

---

build/python/backend/Dockerfile
src/python/requirements.txt
src/python/strelka/tests/test_scan_capa.py

This PR updates CAPA to v5.
Tests have been updated to include additional rule matches in the v5 ruleset. The CAPA tests also saw increases in the timeout time for the CAPA test as some builds seem to take quite some time for those tests.
Required an update to `requirements.txt`:
- `flare-capa`
- `pyelftools`  
Built containers
```
=> [16/18] RUN echo '[+] Run build checks' &&     cd /strelka/strelka/ &&     python3 -m pytest -p no:cacheprovider -s tests/ &&     if false; then python3 -m pytest -s tests_configuration/; fi &&     echo '[+] Done'                       108.3s
=> [17/18] RUN cd /strelka/ &&     rm -rf /strelka/ …
```

Update CAPA to Version 5

---

src/python/strelka/scanners/scan_pe.py

Adding functionality to `ScanPE` in an effort to extract additional rich information such as  `tool version` and `tool ID`.  The rich information can describe the visual studio tool used to compile a PE file.
```
====================== 122 passed, 20 warnings in 54.07s =======================
[+] Done
Removing intermediate container cdd6be58ab9d
---> 7b515d99a812
Step 28/31 : USER root
---> Running in 7471eeca71c5
Removing intermediate container 7471eeca71c5
---> 5012c9e6e217
Step 29/31 : RUN cd /strelka/ &&     rm -rf /strelka/
---> Running in 63a5b59561b9
Removing intermediate container 63a5b59561b9
---> 2e8279525a45
Step 30/31 : RUN rm -rf /etc/strelka/
---> Running in fe4c3632c3af
Removing intermediate container fe4c3632c3af
---> …
```

ScanPE Rich Info Additions

---

src/python/strelka/strelka.py

The default value for the mime_db file must be None in order for it to use the default database file in the `/usr` tree. Defaulting to an empty string `""` causes Magic to throw an exception due to a missing file at that empty path.
This likely only affects users that need to generate the config file via yaml formatters that are unable to convert `None` to `null`.
I did not create an issue. Let me know if you'd like one created and linked to this PR.
Start the backend container with the `tasting.mime_db` setting deleted from the backend config file. The container will crash. Pull the fixed image and start a new container, still with the deleted setting. The container should not crash, and should start up normally. …

python-magic needs a None value to use the default mime DB

---

configs/python/backend/taste/taste.yara
src/python/strelka/config/taste.yara

Include a summary of the change (with required dependencies), any issues it fixes, and relevant motivation and context.
Originally implemented here: https://github.com/sublime-security/strelka/pull/33. No merge conflicts (although that fork does have some moved around scanner config files)
Credit to @alexk307 for the change!
I tested with an extremely minimal file `test.js` with contents:
```
let foo = 'bar'
```
Without this change no yara flavor is returned, and with this change the flavor `javascript_file` is returned. 
**Checklist**

Adds  keyword to js scanner to scan ECMA6 compliant js (#33)

---

src/go/cmd/strelka-frontend/main.go

This allows, but does not require, a client to use GZIP compression when calling Strelka.
Originally implemented in https://github.com/sublime-security/strelka/pull/26
```
opts := []grpc.CallOption{grpc.WaitForReady(true), grpc.UseCompressor(grpcgzip.Name)}
scanFile, err := sc.frontend.ScanFile(ctx, opts...)
```
I modified a client to include the `grpc.UseCompressor(grpcgzip.Name)` option and validated that `grpc: Decompressor is not installed for grpc-encoding "gzip"` is returned without this change. Everything works as normal when this change is included. I also tested without the option to ensure backwards compatibility.
No changes.
**Checklist**

Add import for GRPC gzip compression

---

build/docker-compose-no-build.yaml
build/docker-compose.yaml

Updated the Dockerfile reference for `strelkaui` in the following files:
- `docker-compose.yaml`
- `docker-compose-no-build.yaml`
The image version is now hardcoded instead of using the `latest` tag as that reference doesn't seem to be functioning properly.
I tested the changes by deploying the application using both the `docker-compose.yaml` and `docker-compose-no-build.yaml` files. I verified that the `strelkaui` container was running and that the application was functioning properly.
N/A.
**Checklist**

Update Dockerfile reference for Strelka-UI in docker-compose files

---

.github/workflows/publish_latest.yml

This pull request includes changes to our GitHub Actions workflow, specifically targeting the process of building and pushing Docker images. The new workflow will trigger whenever a new tag is created in the repository.
Images are now being pushed to `https://hub.docker.com/u/target`
**Changes Include:**
- The workflow is now triggered on tag creation instead of push to the publish-images branch.
- The image build and push process has been streamlined using an associative array in Bash. This should make the script more maintainable and easier to expand if we add more components in the future.
- The Dockerfiles' paths and their respective image names have been included in the associative array. This approach simplifies the process of adding or modifying Dockerfiles …

Implement Docker Image Publishing on New Tag Creation

---

misc/build-binaries/build-all-binaries.sh

This change introduces a new shell script for building Go binaries for multiple platforms directly from the root of the Strelka directory. The script simplifies the build process by iterating over each permutation of GOOS (operating system), GOARCH (architecture), and executable name. This script does not introduce new dependencies.
To test the script, navigate to the root of the Strelka directory, and execute the script using the command `bash build-go-binaries.sh`. The script should build each of the specified Go binaries and output them to the root directory. Please ensure that you have Go installed before running the script.
Running the script does not modify Strelka's output. However, it will generate the …

Add multi-platform Go build script for Strelka executables

---

src/go/cmd/strelka-frontend/main.go

When a request includes their own ID, backend container are unable to find the event and data entries in Redis. This is because the keys for both the even and data are set with a UUID generated by the frontend, but when submitting the tasks the ID will the the one provided by the request. This update will update the event and data keys before they are submitting to Redis if an ID exists in the request.
Ran the sample python client included in this repo.
**Checklist**

Fixed bug where tasks wouldn't process if ID was included in the request

---

configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_ocr.py

Adds the ability to take a snapshot of the PDF file's first page as a png in order to run OCR on a PDF
Exploded a PDF file and checked the OCR response contained the text.
**Checklist**

Convert PDF to PNG for OCR

---

src/python/strelka/scanners/scan_onenote.py
src/python/strelka/strelka.py
src/python/strelka/tests/test_scan_onenote.py

**Summary of Change**
This PR introduces some improvements to the `ScanOnenote` class in the `strelka` module and fixes the IOC feature to properly capture and store Indicators of Compromise (IOCs) in file events.
**Changes Made**
1. Added a new constant `ONE_NOTE_MAGIC` for the binary string to search for in the data.
2. In the `ScanOnenote` class, modified the `scan` method to capture statistics on the number of files processed and extracted.
3. Fixed the collection of IOCs during the scanning process.
Tested `ScanOnenote` and `AddIOC` functionality with relevant scanners and files.
N/A
**Checklist**

Improve OneNote File Extraction and Fix IOC Storage

---

.github/workflows/build_fileshot_daily.yml
.github/workflows/build_filestream_daily.yml
.github/workflows/build_oneshot_daily.yml
.github/workflows/build_strelka_daily.yml
README.md
build/python/backend/Dockerfile
build/python/backend/kinetic.list
build/python/backend/lunar.list
build/python/backend/pin.pref
docs/README.md

This PR updates the Strelka backend to support Ubuntu 23.04, includes changes to the README, and updates workflows. Additionally, it introduces `ENV PIP_BREAK_SYSTEM_PACKAGES 1` in the `backend` Dockerfile to address the changes introduced in [PEP 668](https://peps.python.org/pep-0668/).
- Updated the backend to use Ubuntu 23.04.
- Updated relevant documentation in the README.
- Adjusted GitHub workflows to ensure compatibility.
- Added `ENV PIP_BREAK_SYSTEM_PACKAGES 1` in the Dockerfile.
All tests passed successfully, tested submission of various files manually through the UI.
N/A
**Checklist**

Strelka Backend Update: Ubuntu 22.10 to 23.04

---

src/python/strelka/scanners/scan_yara.py
src/python/strelka/tests/fixtures/test_elk_linux_torte.yara
src/python/strelka/tests/test_scan_yara.py

As identified in #410, Strelka will fail to load YARA, and subsequently fail to scan, if an unsupported YARA rule is ingested. This can be fixed by curating YARA rules prior to use in Strelka, however, to account for safe loading, we are now checking for a properly loaded compiled YARA prior to use. 
Note: This _may_ still fail if users remove the default test YARA and push unsupported YARA rules.
A [test](https://github.com/target/strelka/compare/yara-compiled-fix?expand=1#diff-6b04f0ac7aa000b5deffb1642e618f703394aa3d4d465790feb836096334679e) using an [unsupported YARA rule](https://github.com/target/strelka/compare/yara-compiled-fix?expand=1#diff-a66a7924ff4e1bc923d547b6347cedfbf96f2767011847261e42c9923b5f89ca) was created. This …

Safely Account for a YARA Compilation Failure

---

README.md
build/docker-compose.yaml
src/python/strelka/scanners/scan_yara.py
src/python/strelka/tests/test_scan_yara.py

This PR makes a couple changes that assists in YARA loading issues:
1) Ensures that if a `backend.yml` exists without a specific key (e.g., yara.compiled), a default is used to prevent an unhandled exception.
YARA failure prior to fix:
```
strelka-backend-1      | 2023-11-13 18:08:22 - [ERROR] root [strelka.scan_wrapper]: ScanYara: unhandled exception while scanning uid a197de79-b500-4cb0-ae4f-64a14f7c54e6 (see traceback below)
strelka-backend-1      | Traceback (most recent call last):
strelka-backend-1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/strelka.py", line 779, in scan_wrapper
strelka-backend-1      |     self.scan(data, file, options, expire_at)
strelka-backend-1      |   File …
```

ScanYara Safe Key Collection

---

configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_iqy.py
src/python/strelka/scanners/scan_ocr.py
src/python/strelka/scanners/scan_xl4ma.py
src/python/strelka/strelka.py
src/python/strelka/tests/test_scan_iqy.py
src/python/strelka/tests/test_scan_ocr.py
src/python/strelka/tests/test_scan_xl4ma.py

This Pull Request introduces significant enhancements to the `ScanOcr` scanner and general improvements to the handling of Indicators of Compromise (IOCs) in various Strelka scanners.
* **ScanOcr Scanner Changes**
+ **Thumbnail Generation**: The scanner now includes functionality to generate a base64-encoded thumbnail of the scanned image. This feature is controlled by the `create_thumbnail` option and uses PIL for image processing.
+ **Improved OCR Handling:** The OCR process has been refined to support the conversion of PDFs to PNGs for better text extraction. Additionally, the handling of text formatting and splitting has been improved for more accurate results.
This change also adds tests for the new functionality.
* **IOC Handling Improvements**
+ **Uniform …

Enhancement of ScanOcr Scanner and Strelka Scanners with IOC Changes

---

src/go/cmd/strelka-frontend/main.go

After the recent upgrade to Confluent Kafka Go v2, it was found that the ssl.endpoint.identification.algorithm configuration option [defaults to https](https://github.com/confluentinc/librdkafka/issues/4349). In order to maintain the behavior that has already been tested with this producer, this configuration option needs to be set to "none" in order to bypass this default. This PR makes the above change. 
Kafka producer was tested with existing broker to verify config change resolves the issue. Default logging was also tested using locally built containers to ensure that normal behavior of local logging did not change. 
N/A
**Checklist**

Bugfix: Add fix for SSL CA Bundle Verification Issue

---

build/go/frontend/Dockerfile
configs/go/frontend/frontend.yaml
docs/README.md
go.mod
go.sum
src/go/cmd/strelka-frontend/main.go
src/go/pkg/structs/structs.go
src/go/pkg/tossS3/tossS3Delete.go
src/go/pkg/tossS3/tossS3Download.go
src/go/pkg/tossS3/tossS3ListObjects.go
src/go/pkg/tossS3/tossS3PruneLogs.go
src/go/pkg/tossS3/tossS3Upload.go

In the case of an interruption to the Kafka Producer connection to the corresponding broker topic, this PR adds in the option to toggle on a redundancy system such that logs for the past three hours are sent to a remote S3 location so that no data is lost during the Kafka interruption. Once connection to the Kafka broker resumes, either by self-healing or by restarting the frontend, the redundancy logs will be pulled from the remote S3 location and sent in parallel with incoming processed logs. 
This feature is dependent on the Kafka Producer option being set to true in the Dockerfile, and, due to this fact, defaults to false in normal running of the application. 
Code has been tested with a local instance of the Strelka containers. …

Optional Redundancy logging to remote S3 location

---

src/python/strelka/scanners/scan_pe.py
src/python/strelka/tests/test_scan_pe.py

As noted in #433, two conditionals were flipped to incorrect logic, causing a mix of types in string and dictionary fields. This change fixes those conditionals to be more accurate to the original intent.
Closes #433.
Reran tests with valid output
N/A
**Checklist**

ScanPe Fix for Dictionary / Flag Type Change (Fix for #433)

---

src/go/cmd/strelka-filestream/main.go

Comment documented an exclusion in the wrong direction, old files vs. new files via Delta.
This change is a single comment only and should not need testing.

Fix bad filestream comment

---

src/python/strelka/scanners/scan_xml.py

Adds in a mimetype check to verify that the given file is in fact an XML file when an error is thrown by the XML scanner in order to verify that the file in question is a XML file. This is done in the error handling section of the scanner instead of the start of the scanner in order to preserve the validity of the existing test cases. 
Tested with opensource Strelka in order to see results in the results in the StrelkaUI, which will be shown below. Specifically tested with .zip files in order to emulate cases in which this was seen in other worker instances
With the above change, the ScanXML bucket still appears in the UI, though contains only the following flag:
**Checklist**

Add mimetype check for XML files

---

build/docker-compose-no-build.yaml
build/docker-compose.yaml

This pull request adds the `pull_policy: always` option to ensure that Docker Compose always pulls the latest images for the following services:
- `frontend`  (`./build/docker-compose-no-build.yaml`)
- `backend`  (`./build/docker-compose-no-build.yaml`)
- `ui` (`./build/docker-compose.yaml` and `./build/docker-compose-no-build.yaml`)
**Note: This change requires Docker Compose version 3.7 or later.**
Previously, if a user had an older image in their repository, docker would start up the preexisting image, even if it wasn't necessarily the latest image in the remote repository.
To ensure that the latest versions of the images are always used, reducing the risk of running outdated versions.
- Docker Compose version: 3.7+
- Services tested: `frontend`, `backend`, `ui`
1. Update Docker …

Adding Pull Policy to Latest Images

---

.github/workflows/build_strelka_nightly.yml
.github/workflows/build_strelka_on_pull_request.yml
CHANGELOG.md

The nightly build has been failing for several days due to a syntax error in the workflow file caused by the depreciation of [Docker Compose v1](https://docs.docker.com/compose/migrate/). This PR updates the nightly build to reflect this migration. Additionally, updated the changelog to include previous changes to the repo including this change. 
Tested build command used for the nightly workflow build locally and confirmed that command runs successfully.
N/A
**Checklist**

Update Nightly Build Workflow

---

poetry.lock
pyproject.toml

After updating the nightly build to migrate from docker compose v1 to v2, there was still a build issue when running the nightly Strelka build. This PR looks to correct this issue by explicitly defining the setuptools dependency as recommended in [this thread](https://github.com/pypa/pip/issues/12050) in the Python Poetry project repo. Likely this issue has a root cause in the fact that we are using an older version of Poetry, which should be upgraded in the future. 
Tested with local docker build and confirmed that Git Action build worked successfully [in this build](https://github.com/target/strelka/actions/runs/10355797076/job/28664235632). 
N/A
**Checklist**

Explicitly define setuptools dependency

---

README.md

Updating docker-compose to docker compose in README references as the syntax has changed. We will have to review for compatibility (perhaps just have both commands as options)
None yet
N/A
**Checklist**

Updating Docker Compose Reference in README

---

CHANGELOG.md
poetry.lock
pyproject.toml

This PR updates all dependant packages of the project in order to address vulnerability issues, most notably for the certifi, requests, zipp, and setuptools dependencies which had open issues created by dependabot. Additionally, added in "package-mode = false" reference in pyproject.toml file in order to address inconsistency in nightly build which appears to be caused by the default python packaging in poetry builds which is not require to build this project. Finally, updated the changelog with recent changes to the project. 
Tested with local build of the project and local build of Strelka UI. 
N/A
**Checklist**

Package Update for Vulnerabilities

---

build/python/backend/Dockerfile
build/python/backend/mantic.list
build/python/backend/pin.pref
poetry.lock
pyproject.toml
src/python/strelka/scanners/scan_dmg.py
src/python/strelka/scanners/scan_seven_zip.py
src/python/strelka/scanners/scan_udf.py
src/python/strelka/scanners/scan_vhd.py
src/python/strelka/tests/test_scan_dmg.py
src/python/strelka/tests/test_scan_seven_zip.py
src/python/strelka/tests/test_scan_udf.py
src/python/strelka/tests/test_scan_vhd.py

In response to [CVE-2024-11477](https://nvd.nist.gov/vuln/detail/CVE-2024-11477) published on 11/22, this PR updates the version of 7zip from 23.01 to 24.09 in order to patch this vulnerability. Though, it should be noted that this vulnerability is likely unreachable in the current Strelka code execution.
The update to 24.09 means that we are no longer dependent on the archived Ubuntu Mantic version, so the mantic.list and pin.fref files and references were removed. Finally, updated all test cases to reflect the version change. No change is made to the functionality or extraction of metadata due to the change in 7zip versions. 
Additionally re-added setuptools as a Poetry dependency as a stop gap in the short term to stabilize the inconsistent nightly Github …

Upgrading 7zip to version 24.09

---

build/docker-compose-no-build.yaml
build/docker-compose.yaml

Added the `unless-stopped` Restart Policy to the coordinator, gatekeep, ui, and postgresdb docker containers in both the docker-compose.yaml and docker-compose-no-build.yaml files to match the other docker containers in these docker compose files. If a user restarts docker or their server before this change then only then only the jaeger, frontend, backend, and manager docker containers would restart leaving Strelka in a bad state.
Re-deployed a oneshot Strelka instance with this new docker-compose file and ran multiple files through the front end UI which all came back with normal results
N/A
**Checklist**

Added Docker Restart Policies to all docker-compose files so that Strelka restarts in a fully running state.

---

configs/python/backend/backend.yaml
configs/python/backend/taste/taste.yara

It was found that Strelka was not properly classifying docx files, which could lead to ScanDocx/ScanExif not processing files that the scanners should pick up. This PR adds in a simple yara rule "docx_file" to help classifying docx files which are currently coming through as octet-stream. Added the rule to the flavors of both ScanExif and ScanDocx.
Tested to ensure that local build still runs successfully and all tests continue to pass. 
N/A, though more files should now be picked up by ScanDocx/ScanExif 
**Checklist**

Docx Classification Update

---

src/python/strelka/scanners/scan_tlsh.py

Discovered by @ronbarrey, there is a significant difference between `diff` to `diffxlen` hashing functions in the library that creates the TLSH hashes in scanTLSH. The `diffxlen` function compares the data and ignores the length of a file, where the existing `diff` function call will compare the data and the length of a file. 
Using a padded warzone payload, they discovered that there was significantly better attribution to malware family similarities using `diffxlen` over `diff`, as seen below:
`diff` results:
`diffxlen` results:
None, though detection is improved through `diffxlen` usage. 
**Checklist**

ScanTLSH diffxlen Update

---

configs/go/filestream/filestream.yaml
src/go/cmd/strelka-filestream/main.go
src/go/pkg/structs/structs.go

The filestream client name is currently hard coded as 'go-filestream'. This PR makes this client name configurable via an addition to the existing filestream.yaml configuration file. This is useful as it helps differentiates clients coming sending data to centralizated Strelka cluster from different filestream clients. 
Tested with a local build to ensure that the client name is passed along with the requests sent to the cluster. 
N/A, just allows for the existing client name to be more easily changed from the default 'go-filestream' without directly changing the code and rebuilding the image. 
**Checklist**

Configurable Filestream Client Name

---

src/python/strelka/scanners/scan_url.py
src/python/strelka/tests/test_scan_url.py

This PR does additional regex matching to pull out URLs matched by the original regex pattern, and then uses the python validators library to ensure the extracted URL matches the widely accepted URL pattern.
The secondary regex matching was chosen by splitting the generated url string by those characters deemed unsafe in the Internet Engineering Task Force (IETF) [RCF 1738](https://datatracker.ietf.org/doc/html/rfc1738) and excluding the split characters.
Tested with local build to ensure that tests pass and entire application builds successfully. 
No change to output, though note that under the above stipulations, one of the original results "example.com" is not considered a valid URL anymore, and has been removed …

Adding Validation to ScanURL
